Homework React + Typescript
UginB/reviewer-search-app pull request #1
Opened 2023-02-14 18:47 UTC by UginB

Выполнил задание по React:
Нужно сделать одностраничное приложение, которое помогает найти ревьюера.

Функционал:

кнопка настроек, по клику на нее можно переключать видимость настроек.
в настройках 3 поля:
login для ввода логина текущего юзера
repo для указания репозитория для которого ищем ревьюера
blacklist для указания списка login-ов, кто не должен быть ревьюером
состояние настроек сохранять в localStorage
для генерации ревьюера нужна кнопка поиска ревьюера, по клику на которую должен быть выбран рандомный ревьюер из списка контрибьютеров репозитория указанный в пункте 2 настроек, учитывая blacklist пункта 3.
при генерации ревьюера показываем текущего пользователя и перебираемые вами пользователи для ревью(выводим имя и аватар).
Дока по API https://docs.github.com/en/rest.

Макетов нет, можно делать на ваш вкус и цвет, включайте фантазию).
Оцениваться будет реализация, а не визуальная часть.
При написании используем только функциональные компоненты, класс компоненты запрещены.
Код пишем на TS. На реализацию 3 недели, до 15 февраля.
Для создания проекта используем [create-react-app](https://create-react-app.dev/)
Предвкушая вопросы о том, как создать окружение и билд конфиги с тс вот ссылка https://create-react-app.dev/docs/adding-typescript/

2023-02-17 06:57 UTC, AndreyGladkov requested changes
Спасибо за решение, глянул по реакт части. Отписал моменты на которые стоит обратить внимание.

2023-02-17 06:57 UTC, AndreyGladkov commented on src/components/App.tsx
> +export default connect(mapStateToProps, actions)(App);
ого =) неожиданно увидеть этот древний хок, мы даже в лекции его и не рассматривали

2023-02-17 06:57 UTC, AndreyGladkov commented on src/components/SearchOutput.tsx
> +const SearchOutput: FC<SearchOutputProps> = ({userData, reviewer, blacklist, contributors, setReviewer}): JSX.Element => {
Описывать возвращаймое значение в данном случае не имеет смысла, у тебя в React.FC оно уже описано.

2023-02-17 06:57 UTC, AndreyGladkov commented on src/components/SearchOutput.tsx
> +			let count = Math.floor(Math.random() * ((contributors.length - blacklist.length - 1) - 0 + 1) + 0);
в чем тайный смысл -0 +0 ?

2023-02-17 06:57 UTC, AndreyGladkov commented on src/components/SearchOutput.tsx
> +				contributors.filter((item) => !new Set(blacklist).has(item.login as String))
создавать сет на каждую иттерацию не стоит, можно вынести из функции фильтрации, либо просто юзать 
```
blacklist.includes(item.login)
```

2023-02-17 06:57 UTC, AndreyGladkov commented on src/components/SearchOutput.tsx
> +export default connect(mapStateToProps, actions)(SearchOutput);
когда будешь делать редакс, лучше использую хуки.

2023-02-17 06:57 UTC, AndreyGladkov commented on src/components/Settings.tsx
> +	const [activeIndex, setActiveIndex] = useState<number>(2);
jfyi не используй магические числа, как правило используют именованные константы для таких вещей

2023-02-17 06:57 UTC, AndreyGladkov commented on src/hooks/http.hook.tsx
> -    const request = useCallback(async (url: string, method: string = 'GET', body = null, headers = {'Content-Type': 'application/json'}) => {
можно без useCallback, просто если объявить функцию request вне локал скоупа хука useHTTP, где то на 2 строке кода.

2023-02-17 06:57 UTC, AndreyGladkov commented on src/hooks/http.hook.tsx
> +    const request = async (url: string, method: string = 'GET', body = null, headers = {'Content-Type': 'application/json'}) => {
ты тут не используешь никаких реакт хуков или сайд-эффектов, в данном случае это могла бы быть просто функция request без обертки в еще одну функцию.

2023-02-17 07:06 UTC, UginB commented on src/components/SearchOutput.tsx
> +			let count = Math.floor(Math.random() * ((contributors.length - blacklist.length - 1) - 0 + 1) + 0);
забыл удалить)

2023-02-17 07:09 UTC, UginB commented on src/components/Settings.tsx
> +	const [activeIndex, setActiveIndex] = useState<number>(2);
Это кусок из доки библиотеки UI) Учтемс)

2023-02-20 09:27 UTC, AndreyGladkov commented on src/components/SearchOutput.tsx
> +			let count = Math.floor(Math.random() * ((contributors.length - blacklist.length - 1) - 0 + 1) + 0);
а зачем -1+1 =) у тебя же есть searchList так бери от него длину

2023-02-20 09:31 UTC, AndreyGladkov commented on src/components/Settings.tsx
> +		setDropdownOpened(newIndex);
можно проще:
```
setDropdownOpened(!dropdownOpened);
```

2023-02-20 09:39 UTC, AndreyGladkov commented on src/components/Settings.tsx
> +	useEffect(() => setOptions(
а зачем ты это делаешь в эффекте?
Так у тебя может получится двух проходный рендер. 
- сначала вызвали рендер
- эффект сетит новый стейт, запустили update lifecycle
- вызвали снова рендер

в данном случае можно просто + описание типа что-то не айс, в той либе что ты использовал уже есть https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/DropdownItem.d.ts#L9:
```
const [options, setOptions] = useState<Array<DropdownItemProps>(contributors.map(item => {return {key: item.id, value: item.login, text: item.login}}));

2023-02-20 09:49 UTC, UginB commented on src/components/SearchOutput.tsx
> +			let count = Math.floor(Math.random() * ((contributors.length - blacklist.length - 1) - 0 + 1) + 0);
Все, до меня дошло как это должно выглядеть) Спасибо)

2023-02-21 09:00 UTC, AndreyGladkov commented on src/components/Settings.tsx
> +	const optionsContributers: Array<DropdownItemProps> = useMemo(() => {
эта мемоизация не имеет смысла, потому как ты ниже делаешь https://github.com/UginB/reviewer-search-app/pull/1/commits/9dc34a1d09ddf4f280d48e57e55a86793a5a8d45#diff-7fa3d190d6bdec0713023122022fd40027f8fd994b91056bc92f176168734812L91
Для компонента Dropdown она не поможет, arrow func будет создавать новую ссылку на каждый рендер.
В теории если бы у тебя были сложные вычисления то можно мемоизировать чтобы уменьшить cpu bound операции, но в данном случае простой map.

2023-02-21 09:01 UTC, AndreyGladkov approved these changes
Спасибо за решение.

2023-02-24 18:14 UTC, merged